spring:
  application:
    name: finbill-application

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8085/realms/oauth-growtogether-realm
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

  datasource:
    url: jdbc:mysql://localhost:3306/finbill?useSSL=true&serverTimezone=UTC&&createDatabaseIfNotExist=true
    username: root
    password: mysql@237
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    open-in-view: false
    main:
      lazy-initialization: true
jwt:
  auth:
    converter:
      resource-id: aouth-growtogether-api-client
server:
  port: 8080

